apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-log
          emptyDir: {}
      containers:
        - name: logwriter
          image: jonschm/logwriter:1.0
          volumeMounts: # Mount volume
            - name: shared-log
              mountPath: /usr/src/app/files
          env:
            - name: FILE_PATH
              value: /usr/src/app/files/randomLog.txt
        - name: logreader
          image: jonschm/logreader:1.0
          volumeMounts: # Mount volume
            - name: shared-log
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '5000'
            - name: FILE_PATH
              value: /usr/src/app/files/randomLog.txt
