apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - logOutput-pingpong/manifests/base
  - logOutput-pingpong/manifests/logOutput
  - logOutput-pingpong/manifests/pingpong
images:
  - name: PINGPONG/IMAGE # must match what's in your Deployment YAML
    newName: jonschm/pingpong
    newTag: "1.71"
  - name: LOGOUTPUT/IMAGE
    newName: jonschm/log_output
    newTag: "1.7"
