apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./persistentVolumeClaim.yaml
  - ./todoapp-deployment.yaml
  - ./todoapp-service.yaml
  - ./route.yaml
images:
  - name: TODO_APP
    newName: jonschm/todoapp
    newTag: "1.91"
