apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-pvc # name of the volume claim, this will be used in the deployment
  namespace: project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Mi
